// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"

void ui_Apps_screen_init(void)
{
ui_Apps = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Apps, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Apps_Panel = lv_obj_create(ui_Apps);
lv_obj_set_width( ui_Apps_Panel, 235);
lv_obj_set_height( ui_Apps_Panel, 214);
lv_obj_set_x( ui_Apps_Panel, 0 );
lv_obj_set_y( ui_Apps_Panel, 22 );
lv_obj_set_align( ui_Apps_Panel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Apps_Panel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Apps_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_scroll_dir(ui_Apps_Panel, LV_DIR_VER);
lv_obj_set_style_bg_color(ui_Apps_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Apps_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Apps_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Apps_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_Apps_Panel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Apps_Panel, 7, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Apps_Panel, 45, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Apps_Panel, 85, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Calculator_App_Button = ui_App_Button_create(ui_Apps_Panel);
lv_obj_set_x( ui_Calculator_App_Button, 0 );
lv_obj_set_y( ui_Calculator_App_Button, 0 );

lv_label_set_text(ui_comp_get_child(ui_Calculator_App_Button, UI_COMP_APP_BUTTON_APP_LABEL),"Calculator");

lv_img_set_src(ui_comp_get_child(ui_Calculator_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE), &ui_img_calculator_icon_nobackground_png);
lv_img_set_zoom(ui_comp_get_child(ui_Calculator_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE),115);

ui_Compass_App_Button = ui_App_Button_create(ui_Apps_Panel);
lv_obj_set_x( ui_Compass_App_Button, 0 );
lv_obj_set_y( ui_Compass_App_Button, 0 );

lv_label_set_text(ui_comp_get_child(ui_Compass_App_Button, UI_COMP_APP_BUTTON_APP_LABEL),"Compass");

lv_img_set_src(ui_comp_get_child(ui_Compass_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE), &ui_img_compass_png);
lv_img_set_angle(ui_comp_get_child(ui_Compass_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE),300);
lv_img_set_zoom(ui_comp_get_child(ui_Compass_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE),140);

ui_Settings_App_Button = ui_App_Button_create(ui_Apps_Panel);
lv_obj_set_x( ui_Settings_App_Button, 0 );
lv_obj_set_y( ui_Settings_App_Button, 0 );

lv_label_set_text(ui_comp_get_child(ui_Settings_App_Button, UI_COMP_APP_BUTTON_APP_LABEL),"Settings");

lv_img_set_src(ui_comp_get_child(ui_Settings_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE), &ui_img_settings_gear_png);
lv_img_set_zoom(ui_comp_get_child(ui_Settings_App_Button, UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE),90);

ui_Apps_Label_Underline = lv_obj_create(ui_Apps);
lv_obj_set_width( ui_Apps_Label_Underline, 100);
lv_obj_set_height( ui_Apps_Label_Underline, 3);
lv_obj_set_x( ui_Apps_Label_Underline, 0 );
lv_obj_set_y( ui_Apps_Label_Underline, -90 );
lv_obj_set_align( ui_Apps_Label_Underline, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Apps_Label_Underline, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Apps_Label_Underline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Apps_Label_Underline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Apps_Label_Underline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Apps_Label_Underline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Apps_Label_Underline, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Apps_Label_Underline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Apps_Label_Underline, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Apps_Label_Underline, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Apps_Label = lv_label_create(ui_Apps);
lv_obj_set_width( ui_Apps_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Apps_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Apps_Label, 0 );
lv_obj_set_y( ui_Apps_Label, 8 );
lv_obj_set_align( ui_Apps_Label, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Apps_Label,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Apps_Label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Apps_Label,"Apps");
lv_obj_set_style_text_color(ui_Apps_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Apps_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Apps_Label, &ui_font_Comfortaa_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Calculator_App_Button, ui_event_Calculator_App_Button_App_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Compass_App_Button, ui_event_Compass_App_Button_App_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_App_Button, ui_event_Settings_App_Button_App_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Apps, ui_event_Apps, LV_EVENT_ALL, NULL);

}
