// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: My_Watch

#include "../ui.h"

void ui_Notifications_screen_init(void)
{
    ui_Notifications = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Notifications, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Notifications_Label_Underline = lv_obj_create(ui_Notifications);
    lv_obj_set_width(ui_Notifications_Label_Underline, 128);
    lv_obj_set_height(ui_Notifications_Label_Underline, 3);
    lv_obj_set_x(ui_Notifications_Label_Underline, 0);
    lv_obj_set_y(ui_Notifications_Label_Underline, -90);
    lv_obj_set_align(ui_Notifications_Label_Underline, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Notifications_Label_Underline, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Notifications_Label_Underline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Notifications_Label_Underline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Notifications_Label_Underline, lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Notifications_Label_Underline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Notifications_Label = lv_label_create(ui_Notifications);
    lv_obj_set_width(ui_Notifications_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Notifications_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Notifications_Label, 0);
    lv_obj_set_y(ui_Notifications_Label, 8);
    lv_obj_set_align(ui_Notifications_Label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Notifications_Label, "Notifications");
    lv_obj_set_style_text_font(ui_Notifications_Label, &ui_font_Righteous_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Notification_Panel = lv_obj_create(ui_Notifications);
    lv_obj_set_width(ui_Notification_Panel, 204);
    lv_obj_set_height(ui_Notification_Panel, 171);
    lv_obj_set_align(ui_Notification_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Notification_Panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Notification_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Notification_Panel, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Notification_Panel, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Notification_Panel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Notification_Panel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Notification_Panel, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Notification_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Notification_Panel, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Notification_Panel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Notification_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Notification_Panel, 8, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Notification_Panel, 22, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Notification_Panel, 22, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_No_New_Notifications_Label = lv_label_create(ui_Notification_Panel);
    lv_obj_set_width(ui_No_New_Notifications_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_No_New_Notifications_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_No_New_Notifications_Label, 0);
    lv_obj_set_y(ui_No_New_Notifications_Label, -63);
    lv_obj_set_align(ui_No_New_Notifications_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_No_New_Notifications_Label, "No New Notifications");
    lv_obj_add_flag(ui_No_New_Notifications_Label, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_No_New_Notifications_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_No_New_Notifications_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_No_New_Notifications_Label, &ui_font_Music_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Notifications_Gesture_Panel = lv_obj_create(ui_Notifications);
    lv_obj_set_width(ui_Notifications_Gesture_Panel, 267);
    lv_obj_set_height(ui_Notifications_Gesture_Panel, 50);
    lv_obj_set_x(ui_Notifications_Gesture_Panel, -1);
    lv_obj_set_y(ui_Notifications_Gesture_Panel, 93);
    lv_obj_set_align(ui_Notifications_Gesture_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Notifications_Gesture_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Notifications_Gesture_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Notifications_Gesture_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Notifications_Gesture_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Notifications_Gesture_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Notifications, ui_event_Notifications, LV_EVENT_ALL, NULL);

}
