// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"

void ui_Notification_Expand_screen_init(void)
{
ui_Notification_Expand = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Notification_Expand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_Notification_Expand, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Notification_Expand);

ui_Notification_Expand_Source = lv_label_create(ui_Notification_Expand);
lv_obj_set_width( ui_Notification_Expand_Source, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Notification_Expand_Source, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Notification_Expand_Source, 0 );
lv_obj_set_y( ui_Notification_Expand_Source, 95 );
lv_obj_set_align( ui_Notification_Expand_Source, LV_ALIGN_CENTER );
lv_label_set_text(ui_Notification_Expand_Source,"Gmail\n12:34 am");
lv_obj_set_style_text_color(ui_Notification_Expand_Source, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Notification_Expand_Source, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Notification_Expand_Source, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Notification_Expand_Source, &ui_font_Comfortaa_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification_Expand_Text_Box = lv_obj_create(ui_Notification_Expand);
lv_obj_remove_style_all(ui_Notification_Expand_Text_Box);
lv_obj_set_width( ui_Notification_Expand_Text_Box, 184);
lv_obj_set_height( ui_Notification_Expand_Text_Box, 150);
lv_obj_set_align( ui_Notification_Expand_Text_Box, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Notification_Expand_Text_Box,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Notification_Expand_Text_Box, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_Notification_Expand_Text_Box, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_Notification_Expand_Text_Box, LV_DIR_VER);
lv_obj_set_style_outline_color(ui_Notification_Expand_Text_Box, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Notification_Expand_Text_Box, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Notification_Expand_Text_Box, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Notification_Expand_Text_Box, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification_Expand_Title = lv_label_create(ui_Notification_Expand_Text_Box);
lv_obj_set_width( ui_Notification_Expand_Title, lv_pct(100));
lv_obj_set_height( ui_Notification_Expand_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Notification_Expand_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Notification_Expand_Title,"Eden Jordan - Gmail calendar event\n");
lv_obj_set_style_text_align(ui_Notification_Expand_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Notification_Expand_Title, &ui_font_Music_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification_Expand_Text_Divider = lv_obj_create(ui_Notification_Expand_Text_Box);
lv_obj_set_height( ui_Notification_Expand_Text_Divider, 10);
lv_obj_set_width( ui_Notification_Expand_Text_Divider, lv_pct(100));
lv_obj_set_align( ui_Notification_Expand_Text_Divider, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Notification_Expand_Text_Divider, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Notification_Expand_Text_Divider, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Notification_Expand_Text_Divider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Notification_Expand_Text_Divider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Notification_Expand_Text_Divider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Notification_Expand_Text_Divider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification_Expand_Text = lv_label_create(ui_Notification_Expand_Text_Box);
lv_obj_set_width( ui_Notification_Expand_Text, lv_pct(100));
lv_obj_set_height( ui_Notification_Expand_Text, LV_SIZE_CONTENT);   /// 100
lv_label_set_text(ui_Notification_Expand_Text,"\"Writings not that easy, but Grammarly can help. This sentence is grammatically correct but its wordy and hard to read, it undermines the writer’s message and the word choice is bland. Grammarly’s cutting edge technology helps you craft compelling understandable that makes an impact on your reader. Much better.”");
lv_obj_add_flag( ui_Notification_Expand_Text, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Notification_Expand_Text, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_align(ui_Notification_Expand_Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Notification_Expand_Text, &ui_font_Music_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification_Expand_Image_Panel = lv_obj_create(ui_Notification_Expand);
lv_obj_set_width( ui_Notification_Expand_Image_Panel, 40);
lv_obj_set_height( ui_Notification_Expand_Image_Panel, 40);
lv_obj_set_x( ui_Notification_Expand_Image_Panel, -1 );
lv_obj_set_y( ui_Notification_Expand_Image_Panel, -98 );
lv_obj_set_align( ui_Notification_Expand_Image_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Notification_Expand_Image_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Notification_Expand_Image_Panel, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Notification_Expand_Image_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification_Expand_Image = lv_img_create(ui_Notification_Expand_Image_Panel);
lv_img_set_src(ui_Notification_Expand_Image, &ui_img_bellnobackground_png);
lv_obj_set_width( ui_Notification_Expand_Image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Notification_Expand_Image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Notification_Expand_Image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Notification_Expand_Image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Notification_Expand_Image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Notification_Expand_Image,230);

lv_obj_add_event_cb(ui_Notification_Expand, ui_event_Notification_Expand, LV_EVENT_ALL, NULL);

}
