// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: My_Watch

#include "../ui.h"

void ui_Schedule_screen_init(void)
{
ui_Schedule = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Schedule, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Schedule_Label = lv_label_create(ui_Schedule);
lv_obj_set_width( ui_Schedule_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Schedule_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Schedule_Label, 0 );
lv_obj_set_y( ui_Schedule_Label, 8 );
lv_obj_set_align( ui_Schedule_Label, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Schedule_Label,"Schedule");
lv_obj_set_style_text_color(ui_Schedule_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Schedule_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Schedule_Label, &ui_font_Comfortaa_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Schedule_Label_Underline = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Schedule_Label_Underline, 128);
lv_obj_set_height( ui_Schedule_Label_Underline, 3);
lv_obj_set_x( ui_Schedule_Label_Underline, 0 );
lv_obj_set_y( ui_Schedule_Label_Underline, -90 );
lv_obj_set_align( ui_Schedule_Label_Underline, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Schedule_Label_Underline, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Schedule_Label_Underline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Schedule_Label_Underline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Schedule_Label_Underline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Schedule_Label_Underline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel3, 150);
lv_obj_set_height( ui_Panel3, 18);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, -75 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -10 );
lv_obj_set_y( ui_Label2, 0 );
lv_obj_set_align( ui_Label2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label2,"1");

ui_Label1 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label1, 80);
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 30 );
lv_obj_set_y( ui_Label1, 0 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"8:40 - 9:30");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel2, 150);
lv_obj_set_height( ui_Panel2, 18);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -54 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -10 );
lv_obj_set_y( ui_Label3, 0 );
lv_obj_set_align( ui_Label3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label3,"2");

ui_Label4 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label4, 80);
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 30 );
lv_obj_set_y( ui_Label4, 0 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"9:35 - 10:25");
lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel4, 150);
lv_obj_set_height( ui_Panel4, 18);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -33 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -10 );
lv_obj_set_y( ui_Label5, 0 );
lv_obj_set_align( ui_Label5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label5,"RT");

ui_Label6 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label6, 80);
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 30 );
lv_obj_set_y( ui_Label6, 0 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"10:30 - 11:00");
lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel5, 150);
lv_obj_set_height( ui_Panel5, 18);
lv_obj_set_x( ui_Panel5, 0 );
lv_obj_set_y( ui_Panel5, -12 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -10 );
lv_obj_set_y( ui_Label7, 0 );
lv_obj_set_align( ui_Label7, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label7,"3");

ui_Label8 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label8, 80);
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 30 );
lv_obj_set_y( ui_Label8, 0 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"11:05 - 11:55");
lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel6, 150);
lv_obj_set_height( ui_Panel6, 18);
lv_obj_set_x( ui_Panel6, 0 );
lv_obj_set_y( ui_Panel6, 9 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -10 );
lv_obj_set_y( ui_Label9, 0 );
lv_obj_set_align( ui_Label9, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label9,"L");

ui_Label10 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label10, 80);
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 30 );
lv_obj_set_y( ui_Label10, 0 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"11:55 - 12:25");
lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel7, 150);
lv_obj_set_height( ui_Panel7, 18);
lv_obj_set_x( ui_Panel7, 0 );
lv_obj_set_y( ui_Panel7, 30 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -10 );
lv_obj_set_y( ui_Label11, 0 );
lv_obj_set_align( ui_Label11, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label11,"4");

ui_Label12 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label12, 80);
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 30 );
lv_obj_set_y( ui_Label12, 0 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"12:30 - 1:20");
lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel8, 150);
lv_obj_set_height( ui_Panel8, 18);
lv_obj_set_x( ui_Panel8, 0 );
lv_obj_set_y( ui_Panel8, 51 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -10 );
lv_obj_set_y( ui_Label13, 0 );
lv_obj_set_align( ui_Label13, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label13,"P.5");

ui_Label14 = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"8:40 - 9:30");

ui_Panel9 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel9, 150);
lv_obj_set_height( ui_Panel9, 18);
lv_obj_set_x( ui_Panel9, 0 );
lv_obj_set_y( ui_Panel9, 51 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -10 );
lv_obj_set_y( ui_Label15, 0 );
lv_obj_set_align( ui_Label15, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label15,"5");

ui_Label16 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label16, 80);
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 30 );
lv_obj_set_y( ui_Label16, 0 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"1:25 - 2:15");
lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_Schedule);
lv_obj_set_width( ui_Panel10, 150);
lv_obj_set_height( ui_Panel10, 18);
lv_obj_set_x( ui_Panel10, 0 );
lv_obj_set_y( ui_Panel10, 72 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, -10 );
lv_obj_set_y( ui_Label17, 0 );
lv_obj_set_align( ui_Label17, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label17,"6");

ui_Label18 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label18, 80);
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, 30 );
lv_obj_set_y( ui_Label18, 0 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"2:20 - 3:10");
lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Schedule, ui_event_Schedule, LV_EVENT_ALL, NULL);

}
