// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"

void ui_Schedule_screen_init(void)
{
ui_Schedule = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Schedule, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_Schedule, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Schedule);

ui_Schedule_Bar = lv_bar_create(ui_Schedule);
lv_bar_set_value(ui_Schedule_Bar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Schedule_Bar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Schedule_Bar, 186);
lv_obj_set_height( ui_Schedule_Bar, 30);
lv_obj_set_x( ui_Schedule_Bar, 0 );
lv_obj_set_y( ui_Schedule_Bar, 70 );
lv_obj_set_align( ui_Schedule_Bar, LV_ALIGN_CENTER );

ui_Schedule_Name = lv_label_create(ui_Schedule);
lv_obj_set_width( ui_Schedule_Name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Schedule_Name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Schedule_Name, 0 );
lv_obj_set_y( ui_Schedule_Name, 45 );
lv_obj_set_align( ui_Schedule_Name, LV_ALIGN_CENTER );
lv_label_set_text(ui_Schedule_Name,"Passing Period");

ui_Schedule_Time_Start = lv_label_create(ui_Schedule);
lv_obj_set_width( ui_Schedule_Time_Start, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Schedule_Time_Start, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Schedule_Time_Start, 10 );
lv_obj_set_y( ui_Schedule_Time_Start, 45 );
lv_obj_set_align( ui_Schedule_Time_Start, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Schedule_Time_Start,"12:00");

ui_Schedule_Time_End = lv_label_create(ui_Schedule);
lv_obj_set_width( ui_Schedule_Time_End, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Schedule_Time_End, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Schedule_Time_End, -10 );
lv_obj_set_y( ui_Schedule_Time_End, 45 );
lv_obj_set_align( ui_Schedule_Time_End, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Schedule_Time_End,"12:10");

ui_Schedule_Roller = lv_roller_create(ui_Schedule);
lv_roller_set_options( ui_Schedule_Roller, "Band\nRobotics\nMath\nEnglish\nLunch\nFrench\nBiology", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Schedule_Roller, 130);
lv_obj_set_width( ui_Schedule_Roller, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Schedule_Roller, 1 );
lv_obj_set_y( ui_Schedule_Roller, -40 );
lv_obj_set_align( ui_Schedule_Roller, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Schedule_Roller, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_add_event_cb(ui_Schedule, ui_event_Schedule, LV_EVENT_ALL, NULL);

}
