// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: My_Watch

#ifndef _UI_COMP_SETTING_PANEL_H
#define _UI_COMP_SETTING_PANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Setting Panel
#define UI_COMP_SETTING_PANEL_SETTING_PANEL 0
#define UI_COMP_SETTING_PANEL_SETTING_LABEL 1
#define UI_COMP_SETTING_PANEL_SETTING_VALUE 2
#define _UI_COMP_SETTING_PANEL_NUM 3
lv_obj_t *ui_Setting_Panel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
