// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: My_Watch

#ifndef _UI_COMP_APP_BUTTON_H
#define _UI_COMP_APP_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT App Button
#define UI_COMP_APP_BUTTON_APP_BUTTON 0
#define UI_COMP_APP_BUTTON_APP_LABEL 1
#define UI_COMP_APP_BUTTON_APP_IMAGE_PANEL 2
#define UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE 3
#define _UI_COMP_APP_BUTTON_NUM 4
lv_obj_t * ui_App_Button_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
