// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"

void ui_event_comp_Notification_Widget_Notification_Widget( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_Notification_Widget = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      NotificationDismiss_Animation(comp_Notification_Widget[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET_VISIBLE], 0);
}
}

// COMPONENT Notification Widget

lv_obj_t *ui_Notification_Widget_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Notification_Widget;
cui_Notification_Widget = lv_obj_create(comp_parent);
lv_obj_set_width( cui_Notification_Widget, 170);
lv_obj_set_height( cui_Notification_Widget, 55);
lv_obj_set_x( cui_Notification_Widget, 0 );
lv_obj_set_y( cui_Notification_Widget, -43 );
lv_obj_set_align( cui_Notification_Widget, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Notification_Widget, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Notification_Widget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Notification_Widget, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_Notification_Widget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_Notification_Widget, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Notification_Source;
cui_Notification_Source = lv_label_create(cui_Notification_Widget);
lv_obj_set_width( cui_Notification_Source, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Notification_Source, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Notification_Source, -1 );
lv_obj_set_y( cui_Notification_Source, 39 );
lv_obj_set_align( cui_Notification_Source, LV_ALIGN_CENTER );
lv_label_set_text(cui_Notification_Source,"com.android.messages");

lv_obj_t *cui_Notification_Widget_Visible;
cui_Notification_Widget_Visible = lv_obj_create(cui_Notification_Widget);
lv_obj_set_width( cui_Notification_Widget_Visible, 170);
lv_obj_set_height( cui_Notification_Widget_Visible, 56);
lv_obj_set_align( cui_Notification_Widget_Visible, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Notification_Widget_Visible, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Notification_Widget_Visible, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Notification_Title;
cui_Notification_Title = lv_label_create(cui_Notification_Widget_Visible);
lv_obj_set_width( cui_Notification_Title, 112);
lv_obj_set_height( cui_Notification_Title, 10);
lv_obj_set_x( cui_Notification_Title, 10 );
lv_obj_set_y( cui_Notification_Title, -13 );
lv_obj_set_align( cui_Notification_Title, LV_ALIGN_TOP_RIGHT );
lv_label_set_long_mode(cui_Notification_Title,LV_LABEL_LONG_DOT);
lv_label_set_text(cui_Notification_Title,"Dad");
lv_obj_clear_flag( cui_Notification_Title, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_style_text_font(cui_Notification_Title, &ui_font_Music_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Notification_Text;
cui_Notification_Text = lv_label_create(cui_Notification_Widget_Visible);
lv_obj_set_width( cui_Notification_Text, 112);
lv_obj_set_height( cui_Notification_Text, 35);
lv_obj_set_x( cui_Notification_Text, 10 );
lv_obj_set_y( cui_Notification_Text, 2 );
lv_obj_set_align( cui_Notification_Text, LV_ALIGN_TOP_RIGHT );
lv_label_set_long_mode(cui_Notification_Text,LV_LABEL_LONG_DOT);
lv_label_set_text(cui_Notification_Text,"Daddddddddddddddddddddddddddddddddddddddddddddddd");
lv_obj_clear_flag( cui_Notification_Text, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_style_text_font(cui_Notification_Text, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Notification_Image_Panel;
cui_Notification_Image_Panel = lv_obj_create(cui_Notification_Widget_Visible);
lv_obj_set_width( cui_Notification_Image_Panel, 48);
lv_obj_set_height( cui_Notification_Image_Panel, 48);
lv_obj_set_x( cui_Notification_Image_Panel, -58 );
lv_obj_set_y( cui_Notification_Image_Panel, 0 );
lv_obj_set_align( cui_Notification_Image_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Notification_Image_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Notification_Image_Panel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Notification_Image_Panel, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Notification_Image_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Notification_Image;
cui_Notification_Image = lv_img_create(cui_Notification_Image_Panel);
lv_obj_set_width( cui_Notification_Image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Notification_Image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Notification_Image, -1 );
lv_obj_set_y( cui_Notification_Image, -2 );
lv_obj_set_align( cui_Notification_Image, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Notification_Image, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(cui_Notification_Image,150);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NOTIFICATION_WIDGET_NUM);
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET] = cui_Notification_Widget;
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_SOURCE] = cui_Notification_Source;
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET_VISIBLE] = cui_Notification_Widget_Visible;
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET_VISIBLE_NOTIFICATION_TITLE] = cui_Notification_Title;
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET_VISIBLE_NOTIFICATION_TEXT] = cui_Notification_Text;
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET_VISIBLE_NOTIFICATION_IMAGE_PANEL] = cui_Notification_Image_Panel;
children[UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET_VISIBLE_NOTIFICATION_IMAGE_PANEL_NOTIFICATION_IMAGE] = cui_Notification_Image;
lv_obj_add_event_cb(cui_Notification_Widget, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Notification_Widget, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_Notification_Widget, ui_event_comp_Notification_Widget_Notification_Widget, LV_EVENT_ALL, children);
ui_comp_Notification_Widget_create_hook(cui_Notification_Widget);
return cui_Notification_Widget; 
}

