// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: My_Watch

#ifndef _UI_COMP_NOTIFICATION_WIDGET_H
#define _UI_COMP_NOTIFICATION_WIDGET_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Notification Widget
#define UI_COMP_NOTIFICATION_WIDGET_NOTIFICATION_WIDGET 0
#define UI_COMP_NOTIFICATION_WIDGET_SOURCE 1
#define UI_COMP_NOTIFICATION_WIDGET_MAIN 2
#define UI_COMP_NOTIFICATION_WIDGET_MAIN_IMAGE_PANEL 3
#define UI_COMP_NOTIFICATION_WIDGET_MAIN_IMAGE_PANEL_IMAGE 4
#define UI_COMP_NOTIFICATION_WIDGET_MAIN_TITLE 5
#define UI_COMP_NOTIFICATION_WIDGET_MAIN_TEXT 6
#define _UI_COMP_NOTIFICATION_WIDGET_NUM 7
lv_obj_t *ui_Notification_Widget_create(lv_obj_t *comp_parent);
void ui_event_comp_Notification_Widget_Main( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
