// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"


// COMPONENT Setting Panel

lv_obj_t *ui_Setting_Panel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Setting_Panel;
cui_Setting_Panel = lv_obj_create(comp_parent);
lv_obj_set_width( cui_Setting_Panel, 200);
lv_obj_set_height( cui_Setting_Panel, 35);
lv_obj_set_x( cui_Setting_Panel, 0 );
lv_obj_set_y( cui_Setting_Panel, -10 );
lv_obj_set_align( cui_Setting_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Setting_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Setting_Panel, 17, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(cui_Setting_Panel, true, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Setting_Label;
cui_Setting_Label = lv_label_create(cui_Setting_Panel);
lv_obj_set_width( cui_Setting_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Setting_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Setting_Label, LV_ALIGN_LEFT_MID );
lv_obj_set_style_text_font(cui_Setting_Label, &ui_font_Comfortaa_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Setting_Value;
cui_Setting_Value = lv_textarea_create(cui_Setting_Panel);
lv_obj_set_width( cui_Setting_Value, 57);
lv_obj_set_height( cui_Setting_Value, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( cui_Setting_Value, 11 );
lv_obj_set_y( cui_Setting_Value, 0 );
lv_obj_set_align( cui_Setting_Value, LV_ALIGN_RIGHT_MID );
if ("1234567890"=="") lv_textarea_set_accepted_chars(cui_Setting_Value, NULL);
else lv_textarea_set_accepted_chars(cui_Setting_Value, "1234567890");
lv_textarea_set_max_length(cui_Setting_Value,5);
lv_textarea_set_placeholder_text(cui_Setting_Value,"66666");
lv_textarea_set_one_line(cui_Setting_Value,true);
lv_obj_clear_flag( cui_Setting_Value, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_align(cui_Setting_Value, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Setting_Value, &ui_font_Comfortaa_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(cui_Setting_Value, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Setting_Value, lv_color_hex(0x25252E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Setting_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Setting_Value, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Setting_Value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Setting_Value, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Setting_Value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SETTING_PANEL_NUM);
children[UI_COMP_SETTING_PANEL_SETTING_PANEL] = cui_Setting_Panel;
children[UI_COMP_SETTING_PANEL_SETTING_LABEL] = cui_Setting_Label;
children[UI_COMP_SETTING_PANEL_SETTING_VALUE] = cui_Setting_Value;
lv_obj_add_event_cb(cui_Setting_Panel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Setting_Panel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Setting_Panel_create_hook(cui_Setting_Panel);
return cui_Setting_Panel; 
}

