// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"

void ui_comp_App_Button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Notification_Widget_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Setting_Panel_create_hook(lv_obj_t * comp)
{
}
