// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: My_Watch

#include "../ui.h"

// COMPONENT App Button

lv_obj_t *ui_App_Button_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_App_Button;
cui_App_Button = lv_btn_create(comp_parent);
lv_obj_set_width( cui_App_Button, 180);
lv_obj_set_height( cui_App_Button, 40);
lv_obj_set_align( cui_App_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_App_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_App_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_App_Button, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_App_Button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_App_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_App_Label;
cui_App_Label = lv_label_create(cui_App_Button);
lv_obj_set_width( cui_App_Label, 120);
lv_obj_set_height( cui_App_Label, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( cui_App_Label, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_App_Label,"App");
lv_obj_set_style_text_font(cui_App_Label, &ui_font_Comfortaa_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_App_Image_Panel;
cui_App_Image_Panel = lv_obj_create(cui_App_Button);
lv_obj_set_width( cui_App_Image_Panel, 34);
lv_obj_set_height( cui_App_Image_Panel, 34);
lv_obj_set_x( cui_App_Image_Panel, -11 );
lv_obj_set_y( cui_App_Image_Panel, 0 );
lv_obj_set_align( cui_App_Image_Panel, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( cui_App_Image_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_App_Image_Panel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_App_Image_Panel, lv_color_hex(0xFF6B00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_App_Image_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(cui_App_Image_Panel, true, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_App_Image;
cui_App_Image = lv_img_create(cui_App_Image_Panel);
lv_obj_set_width( cui_App_Image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_App_Image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_App_Image, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_App_Image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_App_Image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_APP_BUTTON_NUM);
children[UI_COMP_APP_BUTTON_APP_BUTTON] = cui_App_Button;
children[UI_COMP_APP_BUTTON_APP_LABEL] = cui_App_Label;
children[UI_COMP_APP_BUTTON_APP_IMAGE_PANEL] = cui_App_Image_Panel;
children[UI_COMP_APP_BUTTON_APP_IMAGE_PANEL_APP_IMAGE] = cui_App_Image;
lv_obj_add_event_cb(cui_App_Button, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_App_Button, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_App_Button_create_hook(cui_App_Button);
return cui_App_Button; 
}

