// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: My_Watch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void totimescreen(lv_event_t * e);
void ClockDown(lv_event_t * e);
void notificationdismiss(lv_event_t * e);
void drawnotifications(lv_event_t * e);
void ApplyTheme(lv_event_t * e);
void deletenotification(lv_event_t * e);
void settimerdefault(lv_event_t * e);
void togglealarm1(lv_event_t * e);
void togglealarm2(lv_event_t * e);
void togglealarm3(lv_event_t * e);
void togglealarm4(lv_event_t * e);
void toggleampm(lv_event_t * e);
void setalarm(lv_event_t * e);
void resetstopwatch(lv_event_t * e);
void ToggleStopwatch(lv_event_t * e);
void ToggleTimer(lv_event_t * e);
void timeradjust(lv_event_t * e);
void loadsettings(lv_event_t * e);
void UpdateBrightness(lv_event_t * e);
void ToggleBT(lv_event_t * e);
void ToggleDoNotDisturb(lv_event_t * e);
void ToggleTheme(lv_event_t * e);
void UpdateTestTheme(lv_event_t * e);
void UpdateSettings(lv_event_t * e);
void PowerOff(lv_event_t * e);
void stopanim(lv_event_t * e);
void loadcalc(lv_event_t * e);
void CalcHandle(lv_event_t * e);
void ToggleFlashlight(lv_event_t * e);
void PauseMusic(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
