// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: My_Watch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ClockRight(lv_event_t * e);
void ClockDown(lv_event_t * e);
void ApplyTheme(lv_event_t * e);
void notifslideon(lv_event_t * e);
void notifslideoff(lv_event_t * e);
void NotificationDismiss(lv_event_t * e);
void ScreenBack(lv_event_t * e);
void DrawNotifications(lv_event_t * e);
void DeleteNotification(lv_event_t * e);
void SetTimerDefault(lv_event_t * e);
void togglealarm1(lv_event_t * e);
void togglealarm2(lv_event_t * e);
void togglealarm3(lv_event_t * e);
void togglealarm4(lv_event_t * e);
void toggleampm(lv_event_t * e);
void setalarm(lv_event_t * e);
void VibrateStop(lv_event_t * e);
void ResetStopwatch(lv_event_t * e);
void ToggleStopwatch(lv_event_t * e);
void InitTimer(lv_event_t * e);
void ToggleTimer(lv_event_t * e);
void TimerAdjust(lv_event_t * e);
void LoadSettings(lv_event_t * e);
void UpdateBrightness(lv_event_t * e);
void ToggleBT(lv_event_t * e);
void ToggleDoNotDisturb(lv_event_t * e);
void editSetting(lv_event_t * e);
void UpdateSettings(lv_event_t * e);
void ToggleTheme(lv_event_t * e);
void UpdateTestTheme(lv_event_t * e);
void PowerOff(lv_event_t * e);
void applyKeyboardValue(lv_event_t * e);
void StopAnim(lv_event_t * e);
void LoadCalc(lv_event_t * e);
void CalcHandle(lv_event_t * e);
void ToggleFlashlight(lv_event_t * e);
void DrawMusicInfo(lv_event_t * e);
void DrawMusicTime(lv_event_t * e);
void SetMusicDeafault(lv_event_t * e);
void PauseMusic(lv_event_t * e);
void MusicSkipForward(lv_event_t * e);
void MusicSkipBackward(lv_event_t * e);
void DrawWeather(lv_event_t * e);
void SetWeatherDeafault(lv_event_t * e);
void ClockUpwards(lv_event_t * e);
void ClockLeft(lv_event_t * e);
void InitStepsScreen(lv_event_t * e);
void ResetStorage(lv_event_t * e);
void ResetCounter(lv_event_t * e);
void DrawSchedule(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
