// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: My_Watch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toappsscreen(lv_event_t * e);
void drawnotifications(lv_event_t * e);
void totimersscreen(lv_event_t * e);
void notificationdismiss(lv_event_t * e);
void notificationdismiss(lv_event_t * e);
void generictoclock(lv_event_t * e);
void deletenotification(lv_event_t * e);
void alarmsmovedown(lv_event_t * e);
void alarmsmoveup(lv_event_t * e);
void tosetalarm(lv_event_t * e);
void togglealarm1(lv_event_t * e);
void setalarm2(lv_event_t * e);
void togglealarm2(lv_event_t * e);
void setalarm3(lv_event_t * e);
void togglealarm3(lv_event_t * e);
void setalarm4(lv_event_t * e);
void togglealarm4(lv_event_t * e);
void toggleampm(lv_event_t * e);
void setalarm(lv_event_t * e);
void setalarmscreenback(lv_event_t * e);
void stopwatchmoveup(lv_event_t * e);
void stopwatchmovedown(lv_event_t * e);
void resetstopwatch(lv_event_t * e);
void ToggleStopwatch(lv_event_t * e);
void timersscreenback(lv_event_t * e);
void timermoveup(lv_event_t * e);
void timermovedown(lv_event_t * e);
void ToggleTimer(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void timeradjust(lv_event_t * e);
void UpdateBrightness(lv_event_t * e);
void ToggleBT(lv_event_t * e);
void ToggleDoNotDisturb(lv_event_t * e);
void ToggleTheme(lv_event_t * e);
void UpdateTestTheme(lv_event_t * e);
void UpdateSettings(lv_event_t * e);
void PowerOff(lv_event_t * e);
void UpdateSettings(lv_event_t * e);
void UpdateSettings(lv_event_t * e);
void appsscreenback(lv_event_t * e);
void tocalculatorscreen(lv_event_t * e);
void tocompassscreen(lv_event_t * e);
void tosettingsscreen(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
